### ISSUE TITLE
Redesign online/offline sync items logic

### ISSUE THREAD

**Issue by vanlopes** [meumobi/infobox#17]
In **meumobi-sync.js**, the current logic for sync items on the app causes double callback functions (when online and if there's a list of items on the `localStorage`). This will make issues #12 and #13 more easy to fix and understand.

**Comment by vanlopes** [comment]
The logic will be simple, following this [flowchart](http://www.gliffy.com/go/publish/7626873).

**Comment by elbidone** [comment]
The correct workflow is to read localstorage, if empty then leave empty page. On background try to sync.
Then I think "$scope.items is different from localStorage items?" is not necessary. Because if Etag on local storage is equal on response then do nothing.
So "localStorage["newsList"] is null or empty" seems also unecessary
