### ISSUE TITLE
android back button not work

### ISSUE THREAD

**Issue by elbidone** [meumobi/infobox#18]
if I navigate on Android App and try to use the device back button it doesn't work

Tested on android 4.1.2

**Comment by vanlopes** [comment]
In **meumobi-app.js**, the ```backButton``` function has an invalid function. It should be camelCase in ```.indexof(...)``` on line *162*. But it still don't solve the problem. The function ```$rootScope.go()``` goes back in history, but it still raises an exception.

**Comment by vanlopes** [comment]
Related to the comment above, the exception raises when the back button is clicked because the page lose all its references. The exception "TypeError: Cannot find function undefined" on SyncNews.listItems must have something that is not loaded properly.

**Comment by vanlopes** [comment]
The main problem of this issue is the loss of the ```cordova.device``` reference in the application runtime.

![captura de tela 2015-03-27 as 14 01 26](https://cloud.githubusercontent.com/assets/8545703/6872782/30f79214-d48a-11e4-8671-9fa5f1bf87bd.png)

Here are the steps to reproduce this issue (on Android devices):
1. Open the app
2. Open any article
3. Press device back button

Result: The app goes back to the /list view, but no articles are shown.
