### ISSUE TITLE
if I submit login form with mail and password fields empty it raises an error

### ISSUE THREAD

**Issue by elbidone** [meumobi/infobox#9]
[phonegap] [console.error] TypeError: Cannot read property 'error' of undefined
    at Object.t.Login.loginError (http://192.168.0.6:3000/js/app.min.js:8:4641)
    at Object.t.Login.signin (http://192.168.0.6:3000/js/app.min.js:8:4102)

**Comment by vanlopes** [comment]
The error is caused by the `resp` undefined variable in line *71* on **login_controller.js**.
When the user submits blank fields, the function `loginError()` is raised but no response is sent, causing the variable to be undefined and the attribute `error` inexistent in this context.

The fix to this issue is simply defining this error on `loginError()` in line *44*. To improve security and user experience, we must let the user know even if a single required field is empty. Example:

1. When the user forget to fill the password field:
    * ```$scope.Login.loginError({error:"Blank password field"});```
2. When the user forget to fill the username field:
    * ```$scope.Login.loginError({error:"Blank login field"});```
3. Even if the user forget all the fields:
    * ```$scope.Login.loginError({error:"Blank fields"});```

To improve code quality, security and reusability, we should create custom exceptions with code error, messages and if it's plausible or convenient, the name of the component that caused error.
